# Generated by Django 4.1.5 on 2023-01-08 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trucks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
