# Generated by Django 4.1.5 on 2023-01-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0003_remove_fooditem_stock_remove_fooditem_truck_stock"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
    ]
