# Generated by Django 4.1.5 on 2023-01-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0004_alter_stock_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fooditem",
            name="price",
        ),
        migrations.AddField(
            model_name="stock",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
