# Generated by Django 4.1.5 on 2023-01-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0005_remove_fooditem_price_stock_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="fooditem",
            name="default_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
