# Generated by Django 4.1.5 on 2023-01-08 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0006_fooditem_default_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="truck",
            name="stock",
            field=models.ManyToManyField(through="trucks.Stock", to="trucks.fooditem"),
        ),
        migrations.AlterField(
            model_name="stock",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stocked_items",
                to="trucks.truck",
            ),
        ),
    ]
