# Generated by Django 4.1.5 on 2023-01-08 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0007_truck_stock_alter_stock_truck"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="truck",
            name="stock",
        ),
        migrations.AlterField(
            model_name="stock",
            name="truck",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="trucks.truck"
            ),
        ),
    ]
