# Generated by Django 4.1.5 on 2023-01-08 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0009_fooditem_name_alter_stock_truck"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fooditem",
            old_name="default_price",
            new_name="price",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="price",
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchase_date", models.DateTimeField(auto_now_add=True)),
                (
                    "truck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchases",
                        to="trucks.truck",
                    ),
                ),
            ],
        ),
    ]
