# Generated by Django 4.1.5 on 2023-01-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0010_rename_default_price_fooditem_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="items",
            field=models.ManyToManyField(
                related_name="purchases", to="trucks.fooditem"
            ),
        ),
    ]
