# Generated by Django 4.1.5 on 2023-01-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trucks", "0011_purchase_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="items",
        ),
        migrations.AddField(
            model_name="purchase",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
